module.exports = {
  EMAIL_EXISTS: 'email_exists',
  EMAIL_OR_PASSWORD_DO_NOT_MATCH: 'email_or_password_do_not_match',
  PASSWORD_INVALID: 'password_invalid',
  PASSWORD_MIN_LENGTH: 'password_min_length',
  EMAIL_REQUIRED: 'email_required',
  NAME_REQUIRED: 'name_required',
  SURNAME_REQUIRED: 'surname_required',
  PASSWORD_REQUIRED: 'password_required',
  DATABASE_ERROR: 'database_error',
  TOKEN_REQUIRED: 'token_required',
  TOKEN_INVALID: 'token_invalid',
  PAGE_REQUIRED: 'page_required',
  PER_PAGE_REQUIRED: 'per_page_required',
  PAGE_NUMERIC: 'page_must_be_int',
  PER_PAGE_NUMERIC: 'per_page_must_be_int',
  DEFAULT_ERROR: 'default_error',
  WEET_CONTENT_MAX_LENGTH: 'weet_content_max_length',
  UNAUTHORIZED_ROLE: 'unauthorized_role'
};
