module.exports = {
  ADMIN_ROLE: 'ADMIN',
  REGULAR_ROLE: 'REGULAR',
  DEVELOPER_POSITION: 'Developer',
  LEAD_POSITION: 'Lead',
  TL_POSITION: 'TL',
  EM_POSITION: 'EM',
  HEAD_POSITION: 'HEAD',
  CEO_POSITION: 'CEO',
  DISABLED_TOKENS: 'Disabled_Tokens'
};
